### PR TITLE
INIT message structure size should be 2 in examples

### PR DESCRIPTION
**Pull request by davebshow**
INIT message markers should be `B2`

### CODE REVIEW

**Comment by cleishm** [comment]
@davebshow: thanks for noticing that, and apologies for the delay merging. We should get some more maintainers on this repo :)

**Comment by davebshow** [comment]
No worries. Thanks @cleishm

**Comment by cleishm** [comment]
What's your interest here, @davebshow? Would helping maintain this be of interest?

**Comment by davebshow** [comment]
I wrote a Bolt client/server protocol using Asyncio ([asyncbolt](https://github.com/davebshow/asyncbolt)) last fall as a hobby project. I'd love to help, but it's probably not realistic for me right now. My day job takes up most my coding time now, and I'm not really working with graph dbs anymore.

**Pull request merged**
